version: "3"
services:
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: profiles
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      static-network:
        ipv4_address: 172.20.128.2

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/usr/src/app
    ports:
      - 5000:80
    depends_on:
      - mysql_db
    links:
      - mysql_db
    networks:
      static-network:
        ipv4_address: 172.20.128.3

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
